
type ArtistRequest = {
	artists: {
		idArtist: string
		strArtist: string
		strArtistStripped: string
		strArtistAlternate: string
		strLabel: string
		idLabel: string
		intFormedYear: string
		intBornYear: string
		intDiedYear: string
		strDisbanded: string
		strStyle: string
		strGenre: string
		strMood: string
		strWebsite: string
		strFacebook: string
		strTwitter: string
		strBiographyEN: string
		strBiographyDE: string
		strBiographyFR: string
		strBiographyCN: string
		strBiographyIT: string
		strBiographyJP: string
		strBiographyRU: string
		strBiographyES: string
		strBiographyPT: string
		strBiographySE: string
		strBiographyNL: string
		strBiographyHU: string
		strBiographyNO: string
		strBiographyIL: string
		strBiographyPL: string
		strGender: string
		intMembers: string
		strCountry: string
		strCountryCode: string
		strArtistThumb: string
		strArtistLogo: string
		strArtistClearart: string
		strArtistWideThumb: string
		strArtistFanart: string
		strArtistFanart2: string
		strArtistFanart3: string
		strArtistBanner: string
		strMusicBrainzID: string
		strLastFMChart: string
		intCharted: string
		strLocked: string
	}[]
}

type AlbumRequest = {
	album: {
		idAlbum: string
		idArtist: string
		idLabel: string
		strAlbum: string
		strAlbumStripped: string
		strArtist: string
		strArtistStripped: string
		intYearReleased: string
		strStyle: string
		strGenre: string
		strLabel: string
		strReleaseFormat: string
		intSales: string
		strAlbumThumb: string
		strAlbumThumbHQ: string
		strAlbumThumbBack: string
		strAlbumCDart: string
		strAlbumSpine: string
		strAlbum3DCase: string
		strAlbum3DFlat: string
		strAlbum3DFace: string
		strDescriptionEN: string
		strDescriptionDE: string
		strDescriptionFR: string
		strDescriptionCN: string
		strDescriptionIT: string
		strDescriptionJP: string
		strDescriptionRU: string
		strDescriptionES: string
		strDescriptionPT: string
		strDescriptionSE: string
		strDescriptionNL: string
		strDescriptionHU: string
		strDescriptionNO: string
		strDescriptionIL: string
		strDescriptionPL: string
		intLoved: string
		intScore: string
		intScoreVotes: string
		strReview: string
		strMood: string
		strTheme: string
		strSpeed: string
		strLocation: string
		strMusicBrainzID: string
		strMusicBrainzArtistID: string
		strAllMusicID: string
		strBBCReviewID: string
		strRateYourMusicID: string
		strDiscogsID: string
		strWikidataID: string
		strWikipediaID: string
		strGeniusID: string
		strLyricWikiID: string
		strMusicMozID: string
		strItunesID: string
		strAmazonID: string
		strLocked: string
	}[]
}

type TracksRequest = {
	track: {
		idTrack: string
		idAlbum: string
		idArtist: string
		idLyric: string
		idIMVDB: string
		strTrack: string
		strAlbum: string
		strArtist: string
		strArtistAlternate: string
		intCD: string
		intDuration: string
		strGenre: string
		strMood: string
		strStyle: string
		strTheme: string
		strDescriptionEN: string
		strTrackThumb: string
		strTrackLyrics: string
		strMusicVid: string
		strMusicVidDirector: string
		strMusicVidCompany: string
		strMusicVidScreen1: string
		strMusicVidScreen2: string
		strMusicVidScreen3: string
		intMusicVidViews: string
		intMusicVidLikes: string
		intMusicVidDislikes: string
		intMusicVidFavorites: string
		intMusicVidComments: string
		intTrackNumber: string
		intLoved: string
		intScore: string
		intScoreVotes: string
		intTotalListeners: string
		intTotalPlays: string
		strMusicBrainzID: string
		strMusicBrainzAlbumID: string
		strMusicBrainzArtistID: string
		strLocked: string
	}[]
}
